lovelace:
  mode: yaml
  resources:
    - url: http://127.0.0.1:5000/gallery-card.js
      type: module

default_config:

demo:

sensor:
  - platform: files
    folder: ./www/images
    filter: '*.png'
    name: images
    sort: date

  - platform: files
    folder: ./www/videos
    filter: '*.png'
    name: videos
    sort: date