gallery_card_templates:

views:
  - title: Main
    panel: true
    cards:
      - type: grid
        columns: 2
        cards:
          - type: custom:gallery-card-2024
            entities:
              - sensor.images
            file_name_format: YYYY-MM-DD_hh_mm_ss
            caption_format: H:mm - D/M/YYYY
            menu_alignment: hidden
            reverse_sort: true

          - type: custom:gallery-card-2024
            entities:
              - sensor.videos
            file_name_format: YYYY-MM-DD_hh_mm_ss
            caption_format: H:mm - D/M/YYYY
            menu_alignment: hidden
            reverse_sort: true